-- ESTE SCRIPT DERRUBA O BANCO DE DADOS

-- ESTE SCRIPT NAO DERRUBA USUARIOS OU RETIRA PRIVILEGIOS, PARA ISSO, USE O _DROP DE /Usuarios/

-- DROP BANCO (TABELAS COM SEUS REGISTROS)
DROP DATABASE mydb;